[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "github-repo-recommender"
version = "1.0.0"
description = "An AI-powered GitHub repository recommender using semantic search"
requires-python = ">=3.10,<3.11"
dependencies = [
    "streamlit==1.32.0",
    "sentence-transformers==2.2.2",
    "PyGithub==2.1.1",
    "python-dotenv==1.0.0",
    "pydantic==2.5.2",
    "loguru==0.7.2",
    "huggingface-hub==0.17.3",
    "transformers==4.35.2",
    "torch==2.1.0",
    "numpy==1.24.3",
    "scikit-learn==1.3.2",
    "tqdm==4.66.1"
]