[theme]
# UI customization
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# Streamlit server configuration
port = 8501
enableCORS = false
maxUploadSize = 200
enableXsrfProtection = true

[runner]
# Increase timeouts for package installation
installTimeout = 1800  # 30 minutes
magicEnabled = false

[browser]
# Browser behavior
gatherUsageStats = false
serverAddress = "0.0.0.0"

[client]
# Client configuration
showErrorDetails = true
toolbarMode = "auto"

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s %(levelname)s %(message)s"