[github]
# This is just a template. Set these values in Streamlit Cloud's secrets management
token = ""

[deployment]
# Configuration for deployment environment
environment = "production"
debug = false